import React from 'react';
import { Card } from './Card';
import { SectionTitle } from './SectionTitle';

interface Priority {
  number: number;
  title: string;
  subtitle: string;
  description: string;
  actions: string[];
  brevoHelp: string[];
}

const priorities: Priority[] = [
  {
    number: 1,
    title: 'Better monetize your existing base',
    subtitle: 'Increase the share of revenue generated by CRM',
    description:
      'The goal is to increase from 12% to 20-25% of revenue via email/SMS/push by better activating your existing customer base.',
    actions: [
      'Implement post-purchase upsell scenarios segmented by product category.',
      'Reactivate inactive customers via a multi-channel sequence (email + SMS).',
      'Test regular editorial campaigns to increase engagement.',
    ],
    brevoHelp: [
      'Marketing Automation to orchestrate your scenarios.',
      'Advanced segmentation and CDP to target the right profiles.',
      'Email, SMS, and push channels in a single platform.',
    ],
  },
  {
    number: 2,
    title: 'Improve the LTV/CAC ratio',
    subtitle: 'Make each acquired customer work harder',
    description:
      'By increasing the lifetime value of each customer, you will improve the profitability of your acquisition investments.',
    actions: [
      'Create pack or bundle offers to increase average basket size.',
      'Implement a loyalty program (points, status) to encourage repeat purchases.',
    ],
    brevoHelp: [
      'Brevo Loyalty to manage points and status.',
      'Personalized emails based on purchase history.',
    ],
  },
  {
    number: 3,
    title: 'Stabilize acquisition cost',
    subtitle: 'Reduce dependency on paid media',
    description:
      'Develop proprietary acquisition channels to progressively reduce your dependency on paid channels.',
    actions: [
      'Collect more emails and opt-ins from the first visit.',
      'Implement referral campaigns.',
    ],
    brevoHelp: [
      'Integrated capture forms.',
      'Referral scenarios and unique promo codes.',
    ],
  },
];

export const ActionPlan: React.FC = () => {
  return (
    <section className="mb-12">
      <SectionTitle
        title="Prioritized Action Plan and Brevo Levers"
        subtitle="Three strategic priorities to improve your marketing performance"
      />

      <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">
        {priorities.map((priority) => (
          <Card
            key={priority.number}
            className="border-t-4 border-brevo-green hover:shadow-lg transition-shadow"
          >
            <div className="flex items-center gap-3 mb-4">
              <div className="w-10 h-10 rounded-full bg-brevo-green text-white flex items-center justify-center font-bold text-lg">
                {priority.number}
              </div>
              <div>
                <h3 className="font-bold text-gray-900">{priority.title}</h3>
                <p className="text-sm text-gray-600">{priority.subtitle}</p>
              </div>
            </div>

            <p className="text-gray-700 mb-4 text-sm leading-relaxed">{priority.description}</p>

            <div className="mb-4">
              <h4 className="font-semibold text-gray-900 text-sm mb-2">Concrete actions:</h4>
              <ul className="space-y-2">
                {priority.actions.map((action, index) => (
                  <li key={index} className="flex gap-2 text-sm text-gray-700">
                    <span className="text-brevo-green">•</span>
                    <span>{action}</span>
                  </li>
                ))}
              </ul>
            </div>

            <div className="bg-brevo-light rounded-lg p-4 mt-4">
              <h4 className="font-semibold text-brevo-dark text-sm mb-2">How Brevo helps:</h4>
              <ul className="space-y-1">
                {priority.brevoHelp.map((help, index) => (
                  <li key={index} className="flex gap-2 text-sm text-gray-700">
                    <span className="text-brevo-green">✓</span>
                    <span>{help}</span>
                  </li>
                ))}
              </ul>
            </div>
          </Card>
        ))}
      </div>
    </section>
  );
};
