import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';
import type { MarketingPlan, MarketingProgram, ProgramScenario, ScenarioMessage } from '@/src/types/marketing-plan';

// Helper to get message sequence as array (same logic as ProgramDetails.tsx)
const getMessageSequence = (scenario: ProgramScenario): ScenarioMessage[] => {
  const sequence = scenario.message_sequence;
  if (!sequence) return [];

  if (Array.isArray(sequence)) {
    return sequence;
  }

  // If it's an object, convert to array
  if (typeof sequence === 'object') {
    return Object.entries(sequence).map(([key, value]) => {
      if (typeof value === 'string') {
        return { title: key, content: value };
      }
      return { title: key, ...(value as object) };
    });
  }

  return [];
};

// Brevo brand colors (as mutable arrays for jspdf-autotable compatibility)
const BREVO_GREEN: [number, number, number] = [11, 153, 110]; // #0B996E
const BREVO_LIGHT: [number, number, number] = [232, 245, 241]; // Light green background
const DARK_TEXT: [number, number, number] = [31, 41, 55]; // gray-800
const MEDIUM_TEXT: [number, number, number] = [107, 114, 128]; // gray-500
const WHITE: [number, number, number] = [255, 255, 255];

interface PdfTranslations {
  title: string;
  generatedBy: string;
  generatedOn: string;
  companySummary: string;
  industry: string;
  targetAudience: string;
  employees: string;
  businessModel: string;
  activities: string;
  marketingPrograms: string;
  program: string;
  target: string;
  objective: string;
  kpi: string;
  scenarios: string;
  scenario: string;
  mainMessages: string;
  messageSequence: string;
  howBrevoHelps: string;
  whyBrevoBetter: string;
  omnichannelStrategy: string;
  setupEfficiency: string;
  footer: string;
  page: string;
  of: string;
  personalized: string;
  template: string;
}

const defaultTranslations: PdfTranslations = {
  title: 'Marketing Relationship Plan',
  generatedBy: 'Generated by Brevo',
  generatedOn: 'Generated on',
  companySummary: 'Company Summary',
  industry: 'Industry',
  targetAudience: 'Target Audience',
  employees: 'Employees',
  businessModel: 'Business Model',
  activities: 'Activities',
  marketingPrograms: 'Marketing Programs',
  program: 'Program',
  target: 'Target',
  objective: 'Objective',
  kpi: 'KPI',
  scenarios: 'Scenarios',
  scenario: 'Scenario',
  mainMessages: 'Main Messages',
  messageSequence: 'Message Sequence',
  howBrevoHelps: 'How Brevo Helps You',
  whyBrevoBetter: 'Why Brevo',
  omnichannelStrategy: 'Omnichannel',
  setupEfficiency: 'Setup',
  footer: 'brevo.com | Marketing Relationship Plan',
  page: 'Page',
  of: 'of',
  personalized: 'Personalized',
  template: 'Template'
};

export function generateMarketingPlanPdf(
  plan: MarketingPlan,
  companyName: string,
  isPersonalized: boolean = false,
  translations: Partial<PdfTranslations> = {}
): void {
  const t = { ...defaultTranslations, ...translations };
  const doc = new jsPDF();
  const pageWidth = doc.internal.pageSize.width;
  const pageHeight = doc.internal.pageSize.height;
  const margin = 20;
  const contentWidth = pageWidth - (margin * 2);
  let yPos = margin;

  // Helper to add new page if needed
  const checkPageBreak = (neededSpace: number = 40) => {
    if (yPos + neededSpace > pageHeight - 30) {
      doc.addPage();
      yPos = margin;
      addHeader();
    }
  };

  // Helper to add header on each page
  const addHeader = () => {
    // Top green bar
    doc.setFillColor(...BREVO_GREEN);
    doc.rect(0, 0, pageWidth, 8, 'F');
  };

  // Helper to add footer on each page
  const addFooter = (pageNum: number, totalPages: number) => {
    doc.setFontSize(8);
    doc.setTextColor(...MEDIUM_TEXT);
    doc.text(t.footer, margin, pageHeight - 10);
    doc.text(`${t.page} ${pageNum} ${t.of} ${totalPages}`, pageWidth - margin - 20, pageHeight - 10);
  };

  // ==================== PAGE 1: COVER ====================
  addHeader();

  // Title section with green background
  doc.setFillColor(...BREVO_GREEN);
  doc.roundedRect(margin, 25, contentWidth, 50, 3, 3, 'F');

  doc.setFont('helvetica', 'bold');
  doc.setFontSize(24);
  doc.setTextColor(...WHITE);
  doc.text(t.title, margin + 10, 48);

  // Badge (Personalized / Template)
  doc.setFontSize(10);
  doc.setFillColor(...WHITE);
  doc.roundedRect(margin + 10, 55, 60, 12, 2, 2, 'F');
  doc.setTextColor(...BREVO_GREEN);
  doc.text(isPersonalized ? t.personalized : t.template, margin + 15, 63);

  // Company name
  yPos = 95;
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(18);
  doc.setTextColor(...DARK_TEXT);
  const displayName = companyName || plan.company_summary?.name || 'Your Company';
  doc.text(displayName, margin, yPos);

  // Generation info
  yPos += 15;
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(10);
  doc.setTextColor(...MEDIUM_TEXT);
  const today = new Date().toLocaleDateString('en-US', {
    year: 'numeric',
    month: 'long',
    day: 'numeric'
  });
  doc.text(`${t.generatedOn}: ${today}`, margin, yPos);
  doc.text(t.generatedBy, margin, yPos + 6);

  // ==================== COMPANY SUMMARY ====================
  yPos += 30;
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(14);
  doc.setTextColor(...BREVO_GREEN);
  doc.text(t.companySummary, margin, yPos);

  yPos += 10;
  const summary = plan.company_summary;
  if (summary) {
    // Company info box
    doc.setFillColor(...BREVO_LIGHT);
    doc.roundedRect(margin, yPos, contentWidth, 60, 3, 3, 'F');

    const infoStartY = yPos + 10;
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(10);

    const infoItems = [
      { label: t.industry, value: summary.industry || '-' },
      { label: t.targetAudience, value: summary.target_audience || summary.target || '-' },
      { label: t.employees, value: summary.nb_employees || '-' },
      { label: t.businessModel, value: summary.business_model || '-' }
    ];

    let col1Y = infoStartY;
    let col2Y = infoStartY;
    const colWidth = contentWidth / 2 - 10;

    infoItems.forEach((item, index) => {
      const isLeftCol = index % 2 === 0;
      const x = isLeftCol ? margin + 10 : margin + colWidth + 20;
      const currentY = isLeftCol ? col1Y : col2Y;

      doc.setTextColor(...MEDIUM_TEXT);
      doc.setFont('helvetica', 'bold');
      doc.text(item.label + ':', x, currentY);
      doc.setFont('helvetica', 'normal');
      doc.setTextColor(...DARK_TEXT);

      const valueLines = doc.splitTextToSize(item.value, colWidth - 10);
      doc.text(valueLines, x, currentY + 5);

      if (isLeftCol) {
        col1Y += 15 + (valueLines.length - 1) * 4;
      } else {
        col2Y += 15 + (valueLines.length - 1) * 4;
      }
    });

    yPos += 70;
  }

  // Activities
  if (summary?.activities) {
    checkPageBreak(30);
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(10);
    doc.setTextColor(...MEDIUM_TEXT);
    doc.text(t.activities + ':', margin, yPos);
    doc.setFont('helvetica', 'normal');
    doc.setTextColor(...DARK_TEXT);
    const activityLines = doc.splitTextToSize(summary.activities, contentWidth);
    doc.text(activityLines, margin, yPos + 6);
    yPos += 10 + activityLines.length * 5;
  }

  // ==================== MARKETING PROGRAMS TABLE ====================
  checkPageBreak(60);
  yPos += 10;
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(14);
  doc.setTextColor(...BREVO_GREEN);
  doc.text(t.marketingPrograms, margin, yPos);
  yPos += 8;

  // Convert programs to array
  const programsList: MarketingProgram[] = Array.isArray(plan.programs_list)
    ? plan.programs_list
    : Object.values(plan.programs_list || {});

  if (programsList.length > 0) {
    const tableData = programsList.map((program, index) => [
      (index + 1).toString(),
      program.program_name || program.name || `Program ${index + 1}`,
      program.target || '-',
      program.objective || '-',
      program.kpi || '-'
    ]);

    autoTable(doc, {
      startY: yPos,
      head: [[
        '#',
        t.program,
        t.target,
        t.objective,
        t.kpi
      ]],
      body: tableData,
      theme: 'striped',
      headStyles: {
        fillColor: BREVO_GREEN,
        textColor: WHITE,
        fontStyle: 'bold',
        fontSize: 9
      },
      bodyStyles: {
        fontSize: 8,
        textColor: DARK_TEXT
      },
      alternateRowStyles: {
        fillColor: BREVO_LIGHT
      },
      columnStyles: {
        0: { cellWidth: 10 },
        1: { cellWidth: 35 },
        2: { cellWidth: 35 },
        3: { cellWidth: 45 },
        4: { cellWidth: 40 }
      },
      margin: { left: margin, right: margin }
    });

    // @ts-expect-error - jspdf-autotable adds lastAutoTable to doc
    yPos = doc.lastAutoTable.finalY + 15;
  }

  // ==================== PROGRAM DETAILS ====================
  programsList.forEach((program, programIndex) => {
    checkPageBreak(50);

    // Program header
    doc.setFillColor(...BREVO_GREEN);
    doc.roundedRect(margin, yPos, contentWidth, 12, 2, 2, 'F');
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(11);
    doc.setTextColor(...WHITE);
    const programName = program.program_name || program.name || `Program ${programIndex + 1}`;
    doc.text(`${programIndex + 1}. ${programName}`, margin + 5, yPos + 8);
    yPos += 18;

    // Program description
    if (program.description) {
      doc.setFont('helvetica', 'italic');
      doc.setFontSize(9);
      doc.setTextColor(...MEDIUM_TEXT);
      const descLines = doc.splitTextToSize(program.description, contentWidth);
      doc.text(descLines, margin, yPos);
      yPos += descLines.length * 4 + 5;
    }

    // Scenarios
    const scenarios: ProgramScenario[] = program.scenarios || [];
    if (scenarios.length > 0) {
      scenarios.forEach((scenario, scenarioIndex) => {
        checkPageBreak(60);

        const scenarioTarget = scenario.scenario_target || scenario.target || 'General';
        const scenarioObjective = scenario.scenario_objective || scenario.objective || '-';
        const mainMessages = scenario.main_messages_ideas || scenario.main_message_ideas || scenario.messages || '-';

        // Scenario header
        doc.setFillColor(...BREVO_LIGHT);
        doc.roundedRect(margin + 5, yPos, contentWidth - 10, 8, 1, 1, 'F');
        doc.setFont('helvetica', 'bold');
        doc.setFontSize(9);
        doc.setTextColor(...BREVO_GREEN);
        doc.text(`${t.scenario} ${scenarioIndex + 1}: ${scenarioTarget}`, margin + 10, yPos + 5.5);
        yPos += 12;

        // Scenario details
        doc.setFontSize(8);

        // Target
        doc.setFont('helvetica', 'bold');
        doc.setTextColor(...MEDIUM_TEXT);
        doc.text(t.target + ':', margin + 10, yPos);
        doc.setFont('helvetica', 'normal');
        doc.setTextColor(...DARK_TEXT);
        const targetLines = doc.splitTextToSize(scenarioTarget, contentWidth - 45);
        doc.text(targetLines, margin + 35, yPos);
        yPos += targetLines.length * 4 + 3;

        // Objective
        doc.setFont('helvetica', 'bold');
        doc.setTextColor(...MEDIUM_TEXT);
        doc.text(t.objective + ':', margin + 10, yPos);
        doc.setFont('helvetica', 'normal');
        doc.setTextColor(...DARK_TEXT);
        const objLines = doc.splitTextToSize(scenarioObjective, contentWidth - 45);
        doc.text(objLines, margin + 35, yPos);
        yPos += objLines.length * 4 + 3;

        // Main Messages
        doc.setFont('helvetica', 'bold');
        doc.setTextColor(...MEDIUM_TEXT);
        doc.text(t.mainMessages + ':', margin + 10, yPos);
        doc.setFont('helvetica', 'normal');
        doc.setTextColor(...DARK_TEXT);
        const msgLines = doc.splitTextToSize(mainMessages, contentWidth - 45);
        doc.text(msgLines, margin + 35, yPos);
        yPos += msgLines.length * 4 + 5;

        // Message Sequence (if available)
        const messageSequence = getMessageSequence(scenario);
        if (messageSequence.length > 0) {
          checkPageBreak(30);

          doc.setFont('helvetica', 'bold');
          doc.setFontSize(8);
          doc.setTextColor(...BREVO_GREEN);
          doc.text(t.messageSequence + ':', margin + 10, yPos);
          yPos += 5;

          messageSequence.forEach((message, msgIndex) => {
            checkPageBreak(15);

            const messageTitle = message.title || `Message ${msgIndex + 1}`;
            const messageContent = message.content || message.description || '';

            // Message number circle
            doc.setFillColor(...BREVO_LIGHT);
            doc.circle(margin + 14, yPos + 1.5, 3, 'F');
            doc.setFontSize(7);
            doc.setTextColor(...BREVO_GREEN);
            doc.text(`${msgIndex + 1}`, margin + 12.5, yPos + 3);

            // Message title
            doc.setFont('helvetica', 'bold');
            doc.setFontSize(8);
            doc.setTextColor(...DARK_TEXT);
            doc.text(messageTitle, margin + 22, yPos + 3);
            yPos += 5;

            // Message content (if available)
            if (messageContent) {
              doc.setFont('helvetica', 'normal');
              doc.setFontSize(7);
              doc.setTextColor(...MEDIUM_TEXT);
              const contentLines = doc.splitTextToSize(messageContent, contentWidth - 35);
              doc.text(contentLines, margin + 22, yPos);
              yPos += contentLines.length * 3 + 2;
            }
          });
          yPos += 3;
        }

        yPos += 5;
      });
    }

    yPos += 5;
  });

  // ==================== HOW BREVO HELPS ====================
  const brevoHelp = plan.how_brevo_helps_you;
  if (brevoHelp && brevoHelp.length > 0) {
    checkPageBreak(60);

    doc.setFont('helvetica', 'bold');
    doc.setFontSize(14);
    doc.setTextColor(...BREVO_GREEN);
    doc.text(t.howBrevoHelps, margin, yPos);
    yPos += 10;

    const helpData = brevoHelp.map((item) => [
      item.scenario_name || '-',
      item.why_brevo_is_better || '-',
      item.omnichannel_channels || '-',
      item.setup_efficiency || '-'
    ]);

    autoTable(doc, {
      startY: yPos,
      head: [[
        t.scenario,
        t.whyBrevoBetter,
        t.omnichannelStrategy,
        t.setupEfficiency
      ]],
      body: helpData,
      theme: 'striped',
      headStyles: {
        fillColor: BREVO_GREEN,
        textColor: WHITE,
        fontStyle: 'bold',
        fontSize: 8
      },
      bodyStyles: {
        fontSize: 7,
        textColor: DARK_TEXT
      },
      alternateRowStyles: {
        fillColor: BREVO_LIGHT
      },
      margin: { left: margin, right: margin }
    });
  }

  // ==================== ADD PAGE NUMBERS ====================
  // @ts-expect-error - jsPDF types don't expose getNumberOfPages but it exists
  const totalPages = doc.getNumberOfPages() as number;
  for (let i = 1; i <= totalPages; i++) {
    doc.setPage(i);
    addFooter(i, totalPages);
  }

  // ==================== SAVE PDF ====================
  const fileName = `marketing-plan-${companyName?.toLowerCase().replace(/\s+/g, '-') || 'export'}-${new Date().toISOString().split('T')[0]}.pdf`;
  doc.save(fileName);
}
