'use client';

import { useState } from 'react';
import { FileDown, Loader2 } from 'lucide-react';
import { useLanguage } from '@/contexts/LanguageContext';
import type { MarketingPlan } from '@/src/types/marketing-plan';

interface ExportPdfButtonProps {
  plan: MarketingPlan;
  companyName: string;
  isPersonalized?: boolean;
}

export function ExportPdfButton({
  plan,
  companyName,
  isPersonalized = false
}: ExportPdfButtonProps) {
  const [isExporting, setIsExporting] = useState(false);
  const { t, language } = useLanguage();

  const handleExport = async () => {
    setIsExporting(true);

    try {
      // Dynamic import to avoid SSR issues
      const { generateMarketingPlanPdf } = await import('@/src/utils/pdf-generator');

      // Get translations based on current language
      const pdfTranslations = getPdfTranslations(language, t);

      generateMarketingPlanPdf(plan, companyName, isPersonalized, pdfTranslations);
    } catch (error) {
      console.error('Failed to generate PDF:', error);
    } finally {
      setIsExporting(false);
    }
  };

  return (
    <button
      onClick={handleExport}
      disabled={isExporting}
      className="inline-flex items-center px-3 py-1.5 border border-gray-300 text-sm font-medium rounded-lg text-gray-600 bg-white hover:bg-gray-50 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-brevo-green transition-colors disabled:opacity-50 disabled:cursor-not-allowed"
    >
      {isExporting ? (
        <>
          <Loader2 className="h-4 w-4 mr-1.5 animate-spin" />
          {t.marketingPlan?.exportingPdf || 'Exporting...'}
        </>
      ) : (
        <>
          <FileDown className="h-4 w-4 mr-1.5" />
          {t.marketingPlan?.exportPdf || 'Export PDF'}
        </>
      )}
    </button>
  );
}

// Helper to get PDF translations based on language
function getPdfTranslations(language: string, t: Record<string, unknown>) {
  const mp = (t.marketingPlan || {}) as Record<string, string>;

  const baseTranslations = {
    title: mp.headerTitle || 'Marketing Relationship Plan',
    generatedBy: mp.pdfGeneratedBy || 'Generated by Brevo',
    generatedOn: mp.pdfGeneratedOn || 'Generated on',
    companySummary: mp.companySummary || 'Company Summary',
    industry: mp.industry || 'Industry',
    targetAudience: mp.targetAudience || 'Target Audience',
    employees: mp.employees || 'Employees',
    businessModel: mp.businessModel || 'Business Model',
    activities: mp.pdfActivities || 'Activities',
    marketingPrograms: mp.marketingPrograms || 'Marketing Programs',
    program: mp.program || 'Program',
    target: mp.target || 'Target',
    objective: mp.objective || 'Objective',
    kpi: mp.kpi || 'KPI',
    scenarios: mp.pdfScenarios || 'Scenarios',
    scenario: mp.scenario || 'Scenario',
    mainMessages: mp.mainMessages || 'Main Messages',
    messageSequence: mp.messageSequence || 'Message Sequence',
    howBrevoHelps: mp.howBrevoHelps || 'How Brevo Helps You',
    whyBrevoBetter: mp.whyBrevoBetter || 'Why Brevo',
    omnichannelStrategy: mp.omnichannelStrategy || 'Omnichannel',
    setupEfficiency: mp.setupEfficiency || 'Setup',
    footer: mp.pdfFooter || 'brevo.com | Marketing Relationship Plan',
    page: mp.pdfPage || 'Page',
    of: mp.pdfOf || 'of',
    personalized: mp.personalized || 'Personalized',
    template: mp.template || 'Template'
  };

  // Language-specific overrides
  if (language === 'fr') {
    return {
      ...baseTranslations,
      title: 'Plan Marketing Relationnel',
      generatedBy: 'Généré par Brevo',
      generatedOn: 'Généré le',
      companySummary: 'Résumé de l\'entreprise',
      industry: 'Secteur',
      targetAudience: 'Audience cible',
      employees: 'Employés',
      businessModel: 'Modèle économique',
      activities: 'Activités',
      marketingPrograms: 'Programmes Marketing',
      program: 'Programme',
      target: 'Cible',
      objective: 'Objectif',
      scenarios: 'Scénarios',
      scenario: 'Scénario',
      mainMessages: 'Messages clés',
      messageSequence: 'Séquence de messages',
      howBrevoHelps: 'Comment Brevo vous aide',
      whyBrevoBetter: 'Pourquoi Brevo',
      omnichannelStrategy: 'Omnicanal',
      setupEfficiency: 'Configuration',
      footer: 'brevo.com | Plan Marketing Relationnel',
      page: 'Page',
      of: 'sur',
      personalized: 'Personnalisé',
      template: 'Template'
    };
  }

  if (language === 'de') {
    return {
      ...baseTranslations,
      title: 'Marketing-Beziehungsplan',
      generatedBy: 'Erstellt von Brevo',
      generatedOn: 'Erstellt am',
      companySummary: 'Unternehmensübersicht',
      industry: 'Branche',
      targetAudience: 'Zielgruppe',
      employees: 'Mitarbeiter',
      businessModel: 'Geschäftsmodell',
      activities: 'Aktivitäten',
      marketingPrograms: 'Marketing-Programme',
      program: 'Programm',
      target: 'Ziel',
      objective: 'Zielsetzung',
      scenarios: 'Szenarien',
      scenario: 'Szenario',
      mainMessages: 'Kernbotschaften',
      messageSequence: 'Nachrichtensequenz',
      howBrevoHelps: 'Wie Brevo Ihnen hilft',
      whyBrevoBetter: 'Warum Brevo',
      omnichannelStrategy: 'Omnichannel',
      setupEfficiency: 'Einrichtung',
      footer: 'brevo.com | Marketing-Beziehungsplan',
      page: 'Seite',
      of: 'von',
      personalized: 'Personalisiert',
      template: 'Vorlage'
    };
  }

  if (language === 'es') {
    return {
      ...baseTranslations,
      title: 'Plan de Marketing Relacional',
      generatedBy: 'Generado por Brevo',
      generatedOn: 'Generado el',
      companySummary: 'Resumen de la empresa',
      industry: 'Sector',
      targetAudience: 'Audiencia objetivo',
      employees: 'Empleados',
      businessModel: 'Modelo de negocio',
      activities: 'Actividades',
      marketingPrograms: 'Programas de Marketing',
      program: 'Programa',
      target: 'Objetivo',
      objective: 'Meta',
      scenarios: 'Escenarios',
      scenario: 'Escenario',
      mainMessages: 'Mensajes principales',
      messageSequence: 'Secuencia de mensajes',
      howBrevoHelps: 'Cómo Brevo te ayuda',
      whyBrevoBetter: 'Por qué Brevo',
      omnichannelStrategy: 'Omnicanal',
      setupEfficiency: 'Configuración',
      footer: 'brevo.com | Plan de Marketing Relacional',
      page: 'Página',
      of: 'de',
      personalized: 'Personalizado',
      template: 'Plantilla'
    };
  }

  return baseTranslations;
}

export default ExportPdfButton;
